name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3 ]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, sqlite3
          coverage: none

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Code sniff
        run: vendor/bin/php-cs-fixer fix --dry-run
        env:
          PHP_CS_FIXER_IGNORE_ENV: true

      - name: Execute tests
        run: composer test
